INSERT INTO products (name, description, price, currency_code, created_at, updated_at) VALUES
    ('Cabo XLR Profissional 3m', 'Cabo XLR de 3 metros para microfone e mesa de som.', 14990, 'BRL', NOW(), NOW()),
    ('Microfone Condensador Studio', 'Microfone de estúdio para gravação com captação cristalina.', 32990, 'BRL', NOW(), NOW()),
    ('Headphone Over Ear Pro', 'Fones com isolamento acústico e som balanceado.', 21990, 'BRL', NOW(), NOW()),
    ('Interface de Áudio USB 2x2', 'Interface com entradas e saídas para gravação profissional.', 47990, 'BRL', NOW(), NOW()),
    ('Mesa de Som Digital 8 canais', 'Mesa compacta para home studio e pequenos eventos.', 65990, 'BRL', NOW(), NOW()),
    ('Monitor de Estúdio 5 polegadas', 'Monitor de referência para mixagem e masterização.', 58990, 'BRL', NOW(), NOW()),
    ('Pedal de Distorsão Turbo', 'Pedal com resposta agressiva e ajuste de presença.', 27990, 'BRL', NOW(), NOW()),
    ('Amplificador de Guitarra 30W', 'Amplificador compacto para prática e pequenos shows.', 35990, 'BRL', NOW(), NOW()),
    ('Cabo de Instrumento 6m', 'Cabo reforçado para guitarra, baixo e teclado.', 8990, 'BRL', NOW(), NOW()),
    ('Pickup para Violão Elétrico', 'Conversor com som limpo para violão de palco.', 24990, 'BRL', NOW(), NOW()),
    ('Corda de Nylon Clássica', 'Corda para violão clássico, leve e com timbre doce.', 3290, 'BRL', NOW(), NOW()),
    ('Corda de Aço para Violão', 'Corda bronzeada com boa projeção e durabilidade.', 3890, 'BRL', NOW(), NOW()),
    ('Violão Acústico Folk 6 Cordas', 'Violão profissional com acabamento elegante.', 89990, 'BRL', NOW(), NOW()),
    ('Violão Folk Sunrise', 'Violão popular com boa sonoridade por preço acessível.', 69990, 'BRL', NOW(), NOW()),
    ('Guitarra Elétrica Stratocaster', 'Guitarra clássica com captadores versáteis.', 124990, 'BRL', NOW(), NOW()),
    ('Guitarra Elétrica Les Paul', 'Modelo com som encorpado e visual elegante.', 139990, 'BRL', NOW(), NOW()),
    ('Guitarra Acústica Folk', 'Instrumento ideal para iniciantes e apresentações.', 76990, 'BRL', NOW(), NOW()),
    ('Bateria Eletrônica Compacta', 'Kit compacto para estudo, prática e gravações leves.', 114990, 'BRL', NOW(), NOW()),
    ('Teclado MIDI 49 Teclas', 'Teclado controlável para produção musical digital.', 72990, 'BRL', NOW(), NOW()),
    ('Caixa de Som Portátil 12W', 'Som nítido para eventos pequenos e uso pessoal.', 19990, 'BRL', NOW(), NOW()),
    ('Fone Bluetooth Studio', 'Fone com conectividade wireless e som detalhado.', 24990, 'BRL', NOW(), NOW()),
    ('Teclado Mecânico 60% RGB', 'Teclado esportivo para produtividade e games.', 32990, 'BRL', NOW(), NOW()),
    ('Mouse Gamer 7 Botões', 'Mouse com sensor preciso e ajuste de DPI.', 18990, 'BRL', NOW(), NOW()),
    ('Monitor 27 Full HD', 'Monitor de qualidade para trabalho e multimídia.', 79990, 'BRL', NOW(), NOW()),
    ('SSD NVMe 1TB', 'Armazenamento rápido para PC e laptop.', 34990, 'BRL', NOW(), NOW()),
    ('Notebook ultrafino 14', 'Notebook leve para estudo, trabalho e produtividade.', 289990, 'BRL', NOW(), NOW()),
    ('Roteador Wi-Fi 6', 'Conectividade estável para casa e escritório.', 34990, 'BRL', NOW(), NOW()),
    ('Webcam Full HD 1080p', 'Webcam para videochamada e streaming.', 21990, 'BRL', NOW(), NOW()),
    ('Dock USB-C Hub', 'Hub com múltiplas portas para desktop e notebook.', 17990, 'BRL', NOW(), NOW()),
    ('Placa de Vídeo Gamer', 'Desempenho para jogos e edição leve.', 109990, 'BRL', NOW(), NOW()),
    ('Filamento 3D PLA 1kg', 'Material ideal para impressoras 3D.', 12990, 'BRL', NOW(), NOW()),
    ('Projetor Mini Portable', 'Projetor compacto para apresentações e cinema em casa.', 89990, 'BRL', NOW(), NOW()),
    ('Livro de SQL para Desenvolvedores', 'Guia prático para consultas, joins e otimização.', 6990, 'BRL', NOW(), NOW()),
    ('Go na Prática', 'Livro sobre APIs, concorrência e arquitetura em Go.', 7990, 'BRL', NOW(), NOW()),
    ('Python para Engenharia de Dados', 'Estratégias para processamento e análise em Python.', 8990, 'BRL', NOW(), NOW()),
    ('Arquitetura de Software Limpa', 'Técnicas para criar sistemas sustentáveis e organizados.', 9990, 'BRL', NOW(), NOW()),
    ('APIs REST com Node.js', 'Guia de construção de serviços robustos e testáveis.', 8490, 'BRL', NOW(), NOW()),
    ('Docker para Times de Produto', 'Fundamentos e boas práticas para containers.', 7490, 'BRL', NOW(), NOW()),
    ('Desenvolvimento em Cloud', 'Livro de referência para AWS, Azure e GCP.', 10990, 'BRL', NOW(), NOW()),
    ('Sistemas Distribuídos em Realidade', 'Estratégias para escalabilidade e consistência.', 11990, 'BRL', NOW(), NOW()),
    ('Testes Automatizados em Go', 'Boas práticas para validar APIs e serviços.', 7990, 'BRL', NOW(), NOW()),
    ('Machine Learning com Python', 'Introdução prática com datasets e modelos.', 9890, 'BRL', NOW(), NOW()),
    ('Whey Protein Concentrado', 'Proteína com sabor natural para recuperação muscular.', 12990, 'BRL', NOW(), NOW()),
    ('Creatina Monohidratada', 'Suplemento para desempenho e força muscular.', 8990, 'BRL', NOW(), NOW()),
    ('BCAA em Pó', 'Suplemento para suporte muscular em treinos intensos.', 10990, 'BRL', NOW(), NOW()),
    ('Coqueteleira com Medidor', 'Kit para misturar whey e creatina com praticidade.', 6990, 'BRL', NOW(), NOW()),
    ('Tapete de Yoga 6mm', 'Tapete resistente e antiderrapante para exercícios.', 10990, 'BRL', NOW(), NOW()),
    ('Banda de Resistencia', 'Acessório leve para treino funcional e mobilidade.', 6990, 'BRL', NOW(), NOW()),
    ('Luva de Academia', 'Proteção para puxadas, agachamentos e levantamento.', 8990, 'BRL', NOW(), NOW()),
    ('Garrafão de Água Fitness', 'Garrafa de 1 litro com bocal prático.', 4990, 'BRL', NOW(), NOW()),
    ('Pré-Treino Citrus', 'Suplemento para foco e energia antes do treino.', 11990, 'BRL', NOW(), NOW()),
    ('Barra de Energia Protein', 'Snack reforçado para hidratação e energia.', 6990, 'BRL', NOW(), NOW()),
    ('Corda para Pular Premium', 'Material resistente para cardio e condicionamento.', 5990, 'BRL', NOW(), NOW()),
    ('Bicicleta Ergométrica', 'Equipamento para cardio em casa.', 89990, 'BRL', NOW(), NOW()),
    ('Elástico de Treino', 'Set de elásticos para força e mobilidade.', 4990, 'BRL', NOW(), NOW()),
    ('Proteína Vegana de Ervilha', 'Alternativa plant-based para treino e recuperação.', 13990, 'BRL', NOW(), NOW()),
    ('Omega 3 Premium', 'Suplemento para saúde cardiovascular e desempenho.', 11990, 'BRL', NOW(), NOW()),
    ('Shaker com Tampa', 'Container para misturar suplementos sem respingos.', 3990, 'BRL', NOW(), NOW()),
    ('Ração Premium para Cães', 'Formulação balanceada para alimentação diária.', 8990, 'BRL', NOW(), NOW()),
    ('Ração Gatos Adultos', 'Composição nutritiva para saúde e energia.', 8490, 'BRL', NOW(), NOW()),
    ('Petisco de Carne', 'Snack saboroso para cães e gatos adultos.', 4990, 'BRL', NOW(), NOW()),
    ('Brinquedo de Borracha', 'Brinquedo resistente para mordidas e diversão.', 2990, 'BRL', NOW(), NOW()),
    ('Cama de Pet com Almofada', 'Cama macia para descanso confortável.', 16990, 'BRL', NOW(), NOW()),
    ('Coleira Ajustável', 'Coleira resistente com fechamentos seguros.', 3490, 'BRL', NOW(), NOW()),
    ('Guia Retrátil', 'Acessório pratico para passeios e segurança.', 6990, 'BRL', NOW(), NOW()),
    ('Comedouro Antigolada', 'Comedouro de aço com tampa e base antiderrapante.', 7990, 'BRL', NOW(), NOW()),
    ('Bebedouro de Água', 'Bebedouro contínuo para gatos e cachorros.', 11990, 'BRL', NOW(), NOW()),
    ('Shampoo para Pet', 'Produto para limpeza suave e higiene geral.', 4990, 'BRL', NOW(), NOW()),
    ('Casa de Pet Fibra', 'Mini casinha para descanso e proteção.', 21990, 'BRL', NOW(), NOW()),
    ('Escova para Pelagem', 'Acessório para manter o pelo limpo e saudável.', 3990, 'BRL', NOW(), NOW()),
    ('Transportadora de Pet', 'Caixa para viagens com ventilação e reforço.', 27990, 'BRL', NOW(), NOW()),
    ('Matriz de Corda para Gatos', 'Brinquedo interativo para estimulo e exercício.', 3990, 'BRL', NOW(), NOW()),
    ('Ração Seca para Filhotes', 'Alimentação completa para crescimento e desenvolvimento.', 9990, 'BRL', NOW(), NOW()),
    ('Pente para Pet', 'Ferramenta para remoção de nós e pelos soltos.', 2990, 'BRL', NOW(), NOW()),
    ('Kit de Higiene Pet', 'Conjunto com escova, shampoo e toalha.', 14990, 'BRL', NOW(), NOW()),
    ('Coleira com Identificação', 'Modelo com placa personalizada para passeios.', 8990, 'BRL', NOW(), NOW()),
    ('Areia para Gatos', 'Formulação com baixa poeira e alta absorção.', 7990, 'BRL', NOW(), NOW()),
    ('Bebedouro Automático', 'Bebedouro com filtro para água fresca.', 21990, 'BRL', NOW(), NOW()),
    ('Toldo para Gaiola', 'Acessório de conforto e proteção para gatos.', 6990, 'BRL', NOW(), NOW()),
    ('Saco de Petiscos', 'Petiscos de carne para treinamento e recompensa.', 6990, 'BRL', NOW(), NOW()),
    ('Manta para Pet', 'Manta macia para sofá, cama e transporte.', 7990, 'BRL', NOW(), NOW()),
    ('Pula para Gatos', 'Brinquedo com rodinhas para exercitar atenção.', 3990, 'BRL', NOW(), NOW()),
    ('Kit de Primeiros Socorros Pet', 'Conjunto com algodão, antisséptico e gaze.', 12990, 'BRL', NOW(), NOW()),
    ('Armário para Pet', 'Pequeno móvel para organização de itens e acessórios.', 19990, 'BRL', NOW(), NOW()),
    ('Caixa de Transporte para Cães', 'Modelo leve e ventilado para viagens curtas.', 24990, 'BRL', NOW(), NOW()),
    ('Chapéu de Sol para Pet', 'Acessório para proteção durante passeios ao ar livre.', 4990, 'BRL', NOW(), NOW()),
    ('Sonda de Cachorro de Natação', 'Acessório de segurança para banho e piscina.', 6990, 'BRL', NOW(), NOW());

INSERT INTO inventory (product_id, quantity, updated_at) VALUES
    (89, 12, NOW()),
    (90, 9, NOW()),
    (91, 11, NOW()),
    (92, 7, NOW()),
    (93, 5, NOW()),
    (94, 8, NOW()),
    (95, 10, NOW()),
    (96, 4, NOW()),
    (97, 15, NOW()),
    (98, 6, NOW()),
    (99, 18, NOW()),
    (100, 20, NOW()),
    (101, 3, NOW()),
    (102, 4, NOW()),
    (103, 5, NOW()),
    (104, 2, NOW()),
    (105, 7, NOW()),
    (106, 9, NOW()),
    (107, 11, NOW()),
    (108, 14, NOW()),
    (109, 6, NOW()),
    (110, 18, NOW()),
    (111, 12, NOW()),
    (112, 14, NOW()),
    (113, 9, NOW()),
    (114, 17, NOW()),
    (115, 11, NOW()),
    (116, 8, NOW()),
    (117, 13, NOW()),
    (118, 10, NOW()),
    (119, 7, NOW()),
    (120, 6, NOW()),
    (121, 12, NOW()),
    (122, 8, NOW()),
    (123, 9, NOW()),
    (124, 15, NOW()),
    (125, 14, NOW()),
    (126, 7, NOW()),
    (127, 19, NOW()),
    (128, 4, NOW()),
    (129, 12, NOW()),
    (130, 9, NOW()),
    (131, 11, NOW()),
    (132, 10, NOW()),
    (133, 8, NOW()),
    (134, 13, NOW()),
    (135, 10, NOW()),
    (136, 7, NOW()),
    (137, 9, NOW()),
    (138, 12, NOW()),
    (139, 15, NOW()),
    (140, 11, NOW()),
    (141, 8, NOW()),
    (142, 10, NOW()),
    (143, 6, NOW()),
    (144, 9, NOW()),
    (145, 12, NOW()),
    (146, 7, NOW()),
    (147, 13, NOW()),
    (148, 10, NOW()),
    (149, 11, NOW()),
    (150, 7, NOW()),
    (151, 9, NOW()),
    (152, 5, NOW()),
    (153, 10, NOW()),
    (154, 12, NOW()),
    (155, 8, NOW()),
    (156, 14, NOW()),
    (157, 6, NOW()),
    (158, 11, NOW()),
    (159, 13, NOW()),
    (160, 9, NOW()),
    (161, 12, NOW()),
    (162, 10, NOW()),
    (163, 7, NOW()),
    (164, 11, NOW()),
    (165, 9, NOW()),
    (166, 15, NOW()),
    (167, 8, NOW()),
    (168, 6, NOW()),
    (169, 10, NOW()),
    (170, 8, NOW()),
    (171, 13, NOW()),
    (172, 14, NOW()),
    (173, 7, NOW()),
    (174, 9, NOW()),
    (175, 6, NOW()),
    (176, 10, NOW()),
    (177, 11, NOW()),
    (178, 8, NOW()),
    (179, 12, NOW()),
    (180, 5, NOW()),
    (181, 7, NOW()),
    (182, 9, NOW()),
    (183, 11, NOW()),
    (184, 15, NOW()),
    (185, 12, NOW()),
    (186, 8, NOW()),
    (187, 10, NOW()),
    (188, 7, NOW());
